env:
  es6: true
  browser: true
  commonjs: true

extends:
  - htmlacademy/es6
  - airbnb-typescript

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
  project: ./tsconfig.json

plugins:
  - react

settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
  react:
    version: '16'

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  react/prop-types: off
